### ISSUE TITLE
Maximum callstack size exceeded

### ISSUE THREAD

**Issue by shellka** [socketio/socket.io-emitter#49] opened 2017-01-24 09:07 UTC
Hello, in new version with msgpack-lite i have following issues...
But im not sure, should i post them here or to msgpack...
`
RangeError: Maximum call stack size exceeded
    at I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:237:26
    at Array.forEach (native)
    at obj_to_map (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:237:10)
    at object (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:165:5)
    at encode (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-core.js:23:5)
    at I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:239:7
    at Array.forEach (native)
    at obj_to_map (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:237:10)
    at object (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:165:5)
    at encode (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-core.js:23:5)
    at I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:239:7
    at Array.forEach (native)
    at obj_to_map (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:237:10)
    at object (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:165:5)
    at encode (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-core.js:23:5)
    at I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:239:7
    at Array.forEach (native)
    at obj_to_map (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:237:10)
    at object (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:165:5)
    at encode (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-core.js:23:5)
    at I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:239:7
    at Array.forEach (native)
`
and
`
RangeError: Maximum call stack size exceeded
Something bad happened:  RangeError: Maximum call stack size exceeded
    at EncodeBuffer.reserve (I:\repos\wt-server2\node_modules\msgpack-lite\lib\flex-buffer.js:109:19)
    at EncodeBuffer.reserve (I:\repos\wt-server2\node_modules\msgpack-lite\lib\flex-buffer.js:109:19)
    at Array.<anonymous> (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-uint8.js:11:26)
    at Array.<anonymous> (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-uint8.js:11:26)
    at obj_to_map (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:234:16)
    at object (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:165:5)
    at obj_to_map (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:234:16)
    at encode (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-core.js:23:5)
    at object (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:165:5)
    at I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:239:7
    at encode (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-core.js:23:5)
    at Array.forEach (native)
    at obj_to_map (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:237:10)
    at object (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:165:5)
    at I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:239:7
    at encode (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-core.js:23:5)
    at Array.forEach (native)
    at I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:239:7
    at obj_to_map (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:237:10)
    at Array.forEach (native)
    at object (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:165:5)
    at obj_to_map (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:237:10)
    at object (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:165:5)
    at encode (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-core.js:23:5)
    at encode (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-core.js:23:5)
    at I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:239:7
    at I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:239:7
    at Array.forEach (native)
    at Array.forEach (native)
    at obj_to_map (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:237:10)
    at obj_to_map (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:237:10)
    at object (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:165:5)
    at object (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:165:5)
    at encode (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-core.js:23:5)
    at encode (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-core.js:23:5)
    at I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:239:7
    at I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:239:7
    at Array.forEach (native)
    at Array.forEach (native)
    at obj_to_map (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:237:10)
    at object (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:165:5)
    at encode (I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-core.js:23:5)
    at I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:239:7
    at Array.forEach (native)
I:\repos\wt-server2\node_modules\msgpack-lite\lib\write-type.js:237
    keys.forEach(function(key) {
`

**Comment by okvic77** [comment] 2017-01-28 22:46
It show the same to me, but I was using mongoose and I was trying to send a mongoose object.

I fixed by adding doc.toJSON() when I send the data.

**Comment by toblerpwn** [comment] 2017-03-21 20:23
Also having this issue, and I agree that it's related to Mongoose object (or Object ID) handling. I've been having this problem lately in general across the Node ecosystem where Mongoose's Object IDs are handled funny in one way or another.

In my case, `doc.toJSON()` wasn't a solution because I was actually pulling out only parts of it, and at different times, etc. Instead, I used `JSON.stringify()` on my core object before passing it to my socket message/channel parser.

Honestly I feel the core of this problem lies with Mongoose; most developers are expecting these object IDs to act like Strings, but in weird, dark corners of the code - they don't.

In the mean time, hopefully major packages (like `socket.io-emitter`, etc) can find a solution. I'll admit it's beyond my time (right now) to investigate any deeper. Gotta ship the workaround. =/

**Comment by toblerpwn** [comment] 2017-03-21 21:10
Possible steps to reproduce: send a Mongoose ObjectID as either the `channel` or as part of the `message` in a broadcast from `socket.io-emitter`.

(Perhaps there is more at play here; I will try to find a more vanilla/pure test with actual code and post it, but I suspect simply passing an ObjectID through the system will break per the others in this issue.

**Comment by darrachequesne** [comment] 2017-03-21 21:29
```js
var BSON = require('bson');
var msgpack = require('msgpack-lite');
var ObjectId = BSON.ObjectID;

var id = new ObjectId();
var obj = { _id: id };

console.log('before', obj);
console.log('after', msgpack.decode(msgpack.encode(obj)));
// before { _id: 58d19aa898222666c934f864 }
// after { _id: 
//   { _bsontype: 'ObjectID',
//     id: <Buffer 58 d1 9a a8 98 22 26 66 c9 34 f8 64> } }
```
Is there any recursion in the object you are trying to send?

**Comment by toblerpwn** [comment] 2017-03-21 21:49
Maybe it's recursion in how I'm actually broadcasting?

```
  // get reference to socket.io-emitter
  global.socket_io = {}; // global.socket_io cannot be `undefined` in next line
  global.socket_io.sockets = require('socket.io-emitter')({ host: Redis.preferredSocketHost(), port: Redis.preferredSocketPort() });

// ... do work, define `channel` and `message`

global.socket_io.sockets.in(channel).emit(channel, message);

```

Is that even proper syntax to broadcast still? I am upgrading from `socket.io-emitter` 0.3.0 ~> 2.0 and `socket.io` 1.3.7 ~> 1.7.3, so perhaps it's something more simple (i.e. using legacy/broken syntax).

**Comment by KlonD90** [comment] 2017-03-30 06:30
That's definitely emitter problem with new version

**Comment by darrachequesne** [comment] 2017-05-13 06:42
Closed by https://github.com/socketio/socket.io-emitter/releases/tag/3.0.0 (switched to `notepack`).

**Closed by darrachequesne** 2017-05-13 06:42 UTC
