### ISSUE TITLE
Does it support Acknowledgement as in main Socket.io emitter?

### ISSUE THREAD

**Issue by subenksaha** [socketio/socket.io-emitter#51] opened 2017-04-14 05:51 UTC
I am trying to pass acknowledgement function while emitting to client but it's not working but in socket.io node process it is working file. here is my code below:
```
io
.to(socketId)
.emit("event", data,function (err,message) {
     console.info(message);
     console.error(err);
});
```
the callback function is not called and in java client i am gutting ack function null.

**Comment by darrachequesne** [comment] 2017-04-22 05:10
Duplicate of https://github.com/socketio/socket.io-emitter/issues/50.

**Closed by darrachequesne** 2017-04-22 05:10 UTC
